# docker-compose.yml
# AgriNex V2.0 完整部署配置
# 支持三层架构、MinIO对象存储、MySQL数据库

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: agrinex-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: agrinex_root_password
      MYSQL_DATABASE: agrinex
      MYSQL_USER: agrinex_user
      MYSQL_PASSWORD: agrinex_password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - agrinex-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  # MinIO 对象存储
  minio:
    image: minio/minio:latest
    container_name: agrinex-minio
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DOMAIN: localhost
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - agrinex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: agrinex-redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - agrinex-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MQTT 消息代理
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: agrinex-mosquitto
    restart: always
    env_file:
      - .env
    ports:
      - "1883:1883"
      - "9011:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - agrinex-network
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "health_check"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AgriNex 后端 V2
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agrinex-backend
    restart: always
    env_file:
      - .env
    environment:
      # Flask 配置
      FLASK_ENV: production
      SECRET_KEY: agrinex-production-secret-key-change-me
      
      # 数据库配置
      DATABASE_URL: mysql+pymysql://agrinex_user:agrinex_password@mysql:3306/agrinex
      
      # MinIO 配置
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_SECURE: "false"
      
      # Redis 配置
      REDIS_URL: redis://redis:6379/0
      
      # MQTT 配置
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      
      # JWT 配置
      JWT_SECRET_KEY: jwt-production-secret-change-me
      JWT_ACCESS_TOKEN_EXPIRES: 900
      
      # 本地LLM Studio API 配置
      # 请修改API配置
      OPENAI_API_KEY: not-needed-but-required
      OPENAI_BASE_URL: http://host.docker.internal:1234/v1
      OPENAI_MODEL: qwen2.5-0.5b-instruct-mlx
      
      # 存储配置
      LOCAL_STORAGE_PATH: /app/storage
      
      # 其他配置
      PORT: 8000
      PYTHONPATH: /app
    expose:
      - "8000"
    volumes:
      - backend_storage:/app/storage
      - backend_logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
    networks:
      - agrinex-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # AgriNex 前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agrinex-frontend
    restart: always
    env_file:
      - .env
    environment:
      VITE_API_BASE_URL: "/api"
      VITE_WS_BASE_URL: ""
      VITE_APP_TITLE: AgriNex - 农业物联网平台
      VITE_APP_ENV: production
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - agrinex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 反向代理 - 统一入口，解决CORS问题
  nginx-proxy:
    image: nginx:alpine
    container_name: agrinex-nginx-proxy
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend
    networks:
      - agrinex-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3



volumes:
  mysql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local
  backend_storage:
    driver: local
  backend_logs:
    driver: local

networks:
  agrinex-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
