version: "3.9"

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: agrinex_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agri_iot
      MYSQL_USER: agri_user
      MYSQL_PASSWORD: agri_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - agrinex_network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: agrinex_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - agrinex_network
    restart: unless-stopped

  # MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2
    container_name: agrinex_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - agrinex_network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  agrinex_network:
    driver: bridge
